require:
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Rails/I18nLocaleTexts:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false